shellEmulator: true

trustPolicy: no-downgrade

packages:
  - cli
  - packages/nodes/**
  - packages/plugins/**

overrides:
  vite: 'npm:rolldown-vite@7.2.5'

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@tailwindcss/vite': ^4.1.18
  '@types/micromatch': ^4.0.10
  '@types/node': ^25.0.10
  '@types/node-red': ^1.3.5
  '@vitejs/plugin-vue': ^6.0.3
  '@wry-smile/utils': ^1.1.2
  bumpp: ^10.4.0
  commander: ^14.0.2
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  micromatch: ^4.0.8
  node-red: ^4.1.3
  plop: ^4.0.5
  tsdown: ^0.20.1
  typescript: ^5.9.3
  vite: 'npm:rolldown-vite@7.2.5'
  vite-plugin-singlefile: ^2.3.0
